//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GranitEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GranitEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap add {
            get {
                object obj = ResourceManager.GetObject("add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap add_24 {
            get {
                object obj = ResourceManager.GetObject("add_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string AmountHeaderText {
            get {
                return ResourceManager.GetString("AmountHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Cell.
        /// </summary>
        internal static string AutoSizeColumnModeAllCell {
            get {
                return ResourceManager.GetString("AutoSizeColumnModeAllCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BeneficiaryAccount.
        /// </summary>
        internal static string BeneficiaryAccountHeader {
            get {
                return ResourceManager.GetString("BeneficiaryAccountHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BeneficiaryName.
        /// </summary>
        internal static string BeneficiaryNameHeader {
            get {
                return ResourceManager.GetString("BeneficiaryNameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Row.
        /// </summary>
        internal static string ContextMenuDeleteRow {
            get {
                return ResourceManager.GetString("ContextMenuDeleteRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Selected.
        /// </summary>
        internal static string ContextMenuDeleteSelected {
            get {
                return ResourceManager.GetString("ContextMenuDeleteSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap copy {
            get {
                object obj = ResourceManager.GetObject("copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        internal static string CurrencyHeader {
            get {
                return ResourceManager.GetString("CurrencyHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cut {
            get {
                object obj = ResourceManager.GetObject("cut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date is in the past..
        /// </summary>
        internal static string DateInThePastError {
            get {
                return ResourceManager.GetString("DateInThePastError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save {0}?.
        /// </summary>
        internal static string DoYouWantToSave {
            get {
                return ResourceManager.GetString("DoYouWantToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to error.
        /// </summary>
        internal static string ErrorText {
            get {
                return ResourceManager.GetString("ErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File does not exists! .
        /// </summary>
        internal static string FileDoesntExists {
            get {
                return ResourceManager.GetString("FileDoesntExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap find {
            get {
                object obj = ResourceManager.GetObject("find", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First row reached.
        ///Continue search from the end?.
        /// </summary>
        internal static string FirstRowMsgBoxText {
            get {
                return ResourceManager.GetString("FirstRowMsgBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon GranitBankIcon {
            get {
                object obj = ResourceManager.GetObject("GranitBankIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GranitBankSign {
            get {
                object obj = ResourceManager.GetObject("GranitBankSign", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The account number is invalid..
        /// </summary>
        internal static string InvalidAccountError {
            get {
                return ResourceManager.GetString("InvalidAccountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount has to be a positive whole number..
        /// </summary>
        internal static string InvalidAmountError {
            get {
                return ResourceManager.GetString("InvalidAmountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency is invalid. Only &apos;HUF&apos; is accepted..
        /// </summary>
        internal static string InvalidCurrencyError {
            get {
                return ResourceManager.GetString("InvalidCurrencyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value in the field is not a valid date..
        /// </summary>
        internal static string InvalidDateError {
            get {
                return ResourceManager.GetString("InvalidDateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remittance info is invalid, max 4 line and max 32 char is allowed per line.
        ///Line separator is &apos;|&apos; character..
        /// </summary>
        internal static string InvalidRemittanceInfoError {
            get {
                return ResourceManager.GetString("InvalidRemittanceInfoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid window layout specified, default value applies..
        /// </summary>
        internal static string InvalidWindowLayout {
            get {
                return ResourceManager.GetString("InvalidWindowLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected.
        /// </summary>
        internal static string IsActiveHeaderText {
            get {
                return ResourceManager.GetString("IsActiveHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last row reached. 
        ///Continue search from the beginning?.
        /// </summary>
        internal static string LastRowMsgBoxText {
            get {
                return ResourceManager.GetString("LastRowMsgBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap magnifier {
            get {
                object obj = ResourceManager.GetObject("magnifier", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new {0}.
        /// </summary>
        internal static string NewDocumentName {
            get {
                return ResourceManager.GetString("NewDocumentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following specified text not found:
        ///{0}.
        /// </summary>
        internal static string NotFoundMsgBoxText {
            get {
                return ResourceManager.GetString("NotFoundMsgBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Originator.
        /// </summary>
        internal static string OriginatorHeaderText {
            get {
                return ResourceManager.GetString("OriginatorHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap paste {
            get {
                object obj = ResourceManager.GetObject("paste", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap redo_blue {
            get {
                object obj = ResourceManager.GetObject("redo_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RemittanceInfo.
        /// </summary>
        internal static string RemittanceInfoHeaderText {
            get {
                return ResourceManager.GetString("RemittanceInfoHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Following text is too  long: {0}.
        /// </summary>
        internal static string RemittanceInfoLineTooLongError {
            get {
                return ResourceManager.GetString("RemittanceInfoLineTooLongError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExecutionDate.
        /// </summary>
        internal static string RequestedExecutionDateHeaderText {
            get {
                return ResourceManager.GetString("RequestedExecutionDateHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap search_binoculars_find {
            get {
                object obj = ResourceManager.GetObject("search_binoculars_find", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count: .
        /// </summary>
        internal static string StatusCountAllText {
            get {
                return ResourceManager.GetString("StatusCountAllText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected: .
        /// </summary>
        internal static string StatusCountSeletedText {
            get {
                return ResourceManager.GetString("StatusCountSeletedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum: .
        /// </summary>
        internal static string StatusSumAllText {
            get {
                return ResourceManager.GetString("StatusSumAllText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum of Selected: .
        /// </summary>
        internal static string StatusSumSelectedText {
            get {
                return ResourceManager.GetString("StatusSumSelectedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap subtract {
            get {
                object obj = ResourceManager.GetObject("subtract", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap subtract_24 {
            get {
                object obj = ResourceManager.GetObject("subtract_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap table_row_delete {
            get {
                object obj = ResourceManager.GetObject("table_row_delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap table_row_insert {
            get {
                object obj = ResourceManager.GetObject("table_row_insert", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap undo_blue {
            get {
                object obj = ResourceManager.GetObject("undo_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation {0} at {1}:
        ///{2}
        ///
        ///A new document will be opened..
        /// </summary>
        internal static string ValidationErrorMsg {
            get {
                return ResourceManager.GetString("ValidationErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to warning.
        /// </summary>
        internal static string WarningText {
            get {
                return ResourceManager.GetString("WarningText", resourceCulture);
            }
        }
    }
}
